### ISSUE TITLE
Another solution using only sqlite3

### ISSUE THREAD

**Issue by mingodad** [papachristoumarios/HashCode-Team111#1]
Hello !
I did not participated officially on the Hashcode 2018 but implemented a solution for it that only requires sqlite3 command line and the data files, and thought it could be of your interest to know about it and maybe give you ideas to improve your and maybe mine.

https://github.com/mingodad/sqlite3-hashcode-2018

Cheers !

**Comment by papachristoumarios** [comment]
Hello @mingodad . Your solution surprised me in a very positive way :rocket: ! I am iterating through it and I am going to test it soon! 

Besides this, in case you want to know how our solution works take a look at the README file! 

Cheers!
